---
title: "Skin Temperature"
description: "Computes for each respondent the calibrated skin temperature assuming amp run in DC, according to corresponding gain and chosen temperature scale."
helpUrl: https://go.imotions.com/Skin_Temperature
dependencies:
  sensor: "Biopac"
params:
  token: "xxxxx"
  studyId: "xxxxx"
  respondentId: "xxxxx"
  selectedSensorName: ""
  flowName: "xxxxx"
  iMotionsVersion: "xxxxx"
  GainSelection:
   label: "Select corresponding gain used"
   value: "1"
   selected: "1"
   input: select
   choices: ["0.5", "1", "2", "5"]
  TemperatureScaleSelection:
   label: "Choose temperature scale"
   value: "Fahrenheit (deg F)"
   selected: "Fahrenheit (deg F)"
   input: select
   choices: ["Fahrenheit (deg F)", "Celsius (deg C)"]
output:
  html_document:
    df_print: kable
    code_folding: hide
    code_download: true
---

```{r Setup, include = FALSE, purl = FALSE}
knitr::opts_chunk$set(message = FALSE, results = "asis", dev = "ragg_png")

suppressPackageStartupMessages({
    library(imotionsApi)
    library(signal)
    library(data.table)
    library(stringr)
})
```

```{r Parameters, purl = TRUE}
# Retrieves parameters
gain <- as.numeric(params$GainSelection)
temp_scale <- params$TemperatureScaleSelection
```

```{r Functions specific to this script, purl = FALSE}
#' Retrieve the Skin Temperature data for a given respondent.
#' The signal names are determined automatically.
#'
#' @param study An imStudy object as returned from \code{\link{imStudy}}.
#' @param respondent An imRespondent object as returned from \code{\link{getRespondents}}.
#' @param selected_sensor_name selectedSensorName from software dropdown - cloud value is "" and we use autodetection.
#'
#' @return A data.table containing the requested Skin Temperature data.
getSktData <- function(study, respondent, selected_sensor_name) {
    # Retrieves all sensors for a respondent of interest
    sensors <- getSensors(study, respondent)
    sensors <- sensors[sensor != "R Analysis" & eventSourceType == "Sensor", ]

    # in case a device has been selected, we just use this one
    if (selected_sensor_name != "") {
        device_info <- unlist(str_split(selected_sensor_name, "\\|\\|"))
        selected_sensor <- sensors[sensor == device_info[1] & name == device_info[2] & instance == device_info[3], ]

        if (nrow(selected_sensor) == 0) {
            # Handle the case where multiple stations are used with different devices (i.e. NBC lab setup)
            htmlWarning("The device selected was not found for this respondent, trying autodetection instead.")
            selected_sensor_name <- ""
        } else {
            sensors <- selected_sensor
        }
    }

    if (any(grepl("Biopac", sensors$sensor) & grepl("SKT", sensors$instance))) {
        device_type <- "Biopac"
        signal_instance <- "SKT100C"
        signal_name <- "Raw"
        skt_sensor_idx <- grepl(signal_instance, sensors$instance) & grepl("Biopac", sensors$sensor)
    } else {
        if (selected_sensor_name == "") {
            htmlError("Autodetection could not find any skin temperature sensor.")
        } else {
            htmlError("The device selected do not include any skin temperature signal.")
        }
        return(NULL)
    }

    message(paste(device_type, "identified."))

    # If more than one device has been found by autodetection, throw a warning and select the first one
    if (sum(skt_sensor_idx) > 1) {
        htmlWarning(paste("More than one", device_type, "skin temperature device is present.",
                          "Using the first one for processing."))
    }

    # Select the sensor and signals of interest
    sensor <- sensors[skt_sensor_idx, ][1, ]
    signals <- sensor$signals[[1]]
    selected_signal_names <- grep(paste(signal_name, collapse = "|"), signals, value = TRUE)

    # Retrieve the Skin Temperature data
    skt_data <- getSensorData(study, sensor, selected_signal_names)

    # Renames signal column to Volt
    names(skt_data)[2] <- "Volt"

    instance <- unique(strsplit(paste(sensor$sensor, sensor$instance, sensor$name), "\\s+")[[1]])
    attr(skt_data, "instance") <- paste(gsub(":", "", instance), collapse = " ")
    attr(skt_data, "device") <- device_type

    return(skt_data)
}
```

```{r Connecting to iMotions, purl = FALSE}
# Creating connection and loading respondent
connection <- imConnection(params$token)
study <- imStudy(connection, params$studyId)
respondent <- getRespondent(study, params$respondentId)

study_name <- study$name
respondent_name <- respondent$name
```

```{r Raw data to temperature, purl = FALSE}
# Extracting data
skt_data <- getSktData(study, respondent, selectedSensorName)

# Converting to Fahrenheit and adjusting with corresponding gain
skt_data$`Skin Temperature` <- (skt_data$Volt * gain) + 90

# Skin temperture calculation (convertion into celcius if chosen)
if (temp_scale == "Celcius (deg C)") {
    skt_data$`Skin Temperature` <- round((skt_data$`Skin Temperature` - 30) / 2, 1)
} else {
    skt_data$`Skin Temperature` <- round(skt_data$`Skin Temperature`, 1)
}
```


```{r Upload, purl = FALSE}
# Creates metadata for appropriate grouping of the signal
group <- c("", "Skin Temperature")
metadata <- data.table("Provided By" = "iMotions", "Group" = group)

# Uploading the converted signals
ul_temp_signal <- uploadSensorData(params, study, skt_data, respondent, "Calibrated Skin Temperature",
                                   scriptName = "Skin Temperature", metadata)
```

#### Study: ``r study_name``
#### Respondent: ``r respondent_name``

--- 
This R notebook has performed the following steps:

* Retrieval of the raw signal (Volt, V) from the sensor.

* Generates the calibrated skin temperature in `r temp_scale` based on raw signal amplified by a gain of `r gain`. 

### References

```{r license, echo = FALSE}
# The contents of this notebook are licensed under the MIT license:
# Copyright (c) 2018 iMotions
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
```



