# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1      

      - name: Install R dependencies
        run: |
          install.packages(c('remotes', 'rcmdcheck', 'devtools'))
          remotes::install_deps("imotionsApi", dependencies = TRUE)
        shell: Rscript {0}
      
      - name: Tests
        run: |
          devtools::test("imotionsApi")
        shell: Rscript {0}

      - name: Linter
        run: |
          lintr::lint_package("imotionsApi")
        shell: Rscript {0}

      - name: Check
        run: |
          options(crayon.enabled = TRUE)
          rcmdcheck::rcmdcheck("imotionsApi", args = "--no-manual", error_on = "error")
        shell: Rscript {0}
