# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: R-CMD-check

env:
  USE_BSPM: "true"
  _R_CHECK_FORCE_SUGGESTS_: "false"

jobs:
  R-CMD-check:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      USE_BSPM: "true"
      _R_CHECK_FORCE_SUGGESTS_: "false"
    steps:
      - uses: actions/checkout@v2

      - name: Bootstrap
        run: |
          cd imotionsApi
          curl -OLs https://eddelbuettel.github.io/r-ci/run.sh
          chmod 0755 run.sh
          ./run.sh bootstrap

      - name: Dependencies
        run: |
          cd imotionsApi
          sudo apt install r-cran-rcmdcheck
          ./run.sh install_all

      - name: Run linter
        run: |
          lintr::lint_package("imotionsApi")
        shell: Rscript {0}
      
      - name: Check
        run: |
          options(crayon.enabled = TRUE)
          rcmdcheck::rcmdcheck("imotionsApi", args = "--no-manual", error_on = "error")
        shell: Rscript {0}
