name: R test, lint & check, build, release

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - main
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  checks: write
  pull-requests: write
  issues: read

jobs:
  R-test-lint-build-release:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.0'
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, any::lintr
          needs: check, lint
          working-directory: './imotionsApi'

      - name: Run linter
        run: |
          lintr::lint_package('./imotionsApi')
        shell: Rscript {0}
        env:
          LINTR_ERROR_ON_LINT: true

      - name: Get current date
        id: date
        run: echo "datetime=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Fix version number for snapshot
        if: ${{ github.event_name != 'push' || !startsWith(github.ref, 'refs/tags/v') }}
        run: |
          sed -i 's/0000000000/${{ steps.date.outputs.datetime }}/' imotionsApi/DESCRIPTION
        shell: bash

      - name: Get the version from tag
        id: get_version
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Fix version number for release
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
        run: |
          sed -i "/^Version:/c\Version: ${{ steps.get_version.outputs.VERSION }}" imotionsApi/DESCRIPTION
        shell: bash

      - uses: r-lib/actions/check-r-package@v2
        with:
          error-on: '"error"'
          check-dir: '"check"'
          working-directory: './imotionsApi'
          args: 'c("--no-manual", "--as-cran", "--no-multiarch")'

      - name: Publish snapshot
        uses: softprops/action-gh-release@v1
        if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true) }}
        with:
          tag_name: "snapshot-${{ steps.date.outputs.datetime }}"
          prerelease: true
          name: "Snapshot ${{ steps.date.outputs.datetime }}"
          files: |
            LICENSE
            ./imotionsApi/check/*.tar.gz

      - name: Publish tagged release
        uses: softprops/action-gh-release@v1
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
        with:
          files: |
            LICENSE
            ./imotionsApi/check/*.tar.gz

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action/windows@v2
        if: always()
        with:
          files: './imotionsApi/check/imotionsApi.Rcheck/tests/test-results-tests.xml'