# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
  pull_request:
    types: [closed, opened, synchronize]
    branches:
      - main

name: R test, lint & check, build, release

jobs:
  R-test-lint-build-release:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.0'
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, any::lintr
          needs: check, lint
          working-directory: './imotionsApi'

      - name: Run linter
        run: |
            lintr::lint_package('./imotionsApi')
        shell: Rscript {0}
        env:
          LINTR_ERROR_ON_LINT: true
          
      - name: Get current date
        id: date
        run: echo "datetime=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT
        shell: bash
        
      - name: Fix version number for snapshot
        run: |
          sed -i 's/0000000000/${{ steps.date.outputs.datetime }}/' imotionsApi/DESCRIPTION

      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Remove snapshot build and fix version number for release
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          sed -i "/^Version:/c\Version: ${{ steps.get_version.outputs.VERSION }}" imotionsApi/DESCRIPTION

      - uses: r-lib/actions/check-r-package@v2
        with:
          error-on: '"error"'
          check-dir: '"check"'
          working-directory: './imotionsApi'
          args: 'c("--no-manual", "--as-cran", "--no-multiarch")'

      - name: Publish snapshot
        uses: softprops/action-gh-release@v1
        if: ${{ (github.event.pull_request.merged == true) && !(startsWith(github.ref, 'refs/tags/v')) }}
        with:
          tag_name: "snapshot-${{ steps.date.outputs.datetime }}"
          prerelease: true
          name: "Snapshot ${{ steps.date.outputs.datetime }}"
          files: |
            LICENSE
            ./imotionsApi/check/*.tar.gz

      - name: Publish tagged release
        uses: softprops/action-gh-release@v1
        if: ${{ (github.event.pull_request.merged == true) && (startsWith(github.ref, 'refs/tags/v')) }}
        with:
          files: |
            LICENSE
            ./imotionsApi/check/*.tar.gz

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action/composite@v1
        if: always()
        with:
          files: './imotionsApi/check/imotionsApi.Rcheck/tests/test-results-tests.xml'